version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/actions-runner/_work/BE-MOOD/BE-MOOD 
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterAllowTraffic:
  - location: deploy.sh 
    timeout: 120
