name: mood-BE

on:
  push:
    branches:
      - feature/*
      - dev
      - main
  pull_request:
    branches:
      - feature/*
      - dev
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - run: npm i
      - run: pm2 restart app
